Feature/logging conflict resolution (#76)
* Implement configurable logging callback

* Fix compilation error: include cfd_status.h in logging.c

* Fix compilation error: include cfd_status.h in test_logging.c